# @package _global_
scenario_name: backtranslation/tr
test_file: tr/test_en_tr_bt.json
do_train: false
do_eval: false
evaluate_during_training: false
eval_all_checkpoints: false
model_name_or_path: ./experiments/binary_relation_clf/in_language/en/${run_id}

defaults:
  - inlang_en
