# @package _global_
scenario_name: backtranslation/de
test_file: de/test_en_de_bt.json
do_train: false
do_eval: false
evaluate_during_training: false
eval_all_checkpoints: false
model_name_or_path: ./experiments/binary_relation_clf/in_language/en/${run_id}

defaults:
  - inlang_en
