# @package _global_
scenario_name: in_language/hu
model_name_or_path: bert-base-multilingual-cased
data_dir: ./data/hu/
train_file: train_hu.json
dev_file: dev_hu.json
test_file: test_hu.json
learning_rate: 1e-5
