# @package _global_
scenario_name: multi_language/de
additional_train_files: de/train_de.json
additional_dev_files: de/dev_de.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: de/test_de.json

defaults:
  - crosslang_en
