# @package _global_
scenario_name: multi_language/hu
additional_train_files: hu/train_hu.json
additional_dev_files: hu/dev_hu.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: hu/test_hu.json

defaults:
  - crosslang_en
