# @package _global_
scenario_name: multi_language/tr
additional_train_files: tr/train_tr.json
additional_dev_files: tr/dev_tr.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: tr/test_tr.json

defaults:
  - crosslang_en
