# @package _global_
scenario_name: multi_language/pl
additional_train_files: pl/train_pl.json
additional_dev_files: pl/dev_pl.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: pl/test_pl.json

defaults:
  - crosslang_en
