# @package _global_
scenario_name: multi_language/es
additional_train_files: es/train_es.json
additional_dev_files: es/dev_es.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: es/test_es.json

defaults:
  - crosslang_en
