# @package _global_
scenario_name: multi_language/fr
additional_train_files: fr/train_fr.json
additional_dev_files: fr/dev_fr.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: fr/test_fr.json

defaults:
  - crosslang_en
