# @package _global_
scenario_name: multi_language/ja
additional_train_files: ja/train_ja.json
additional_dev_files: ja/dev_ja.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: ja/test_ja.json

defaults:
  - crosslang_en
