# @package _global_
scenario_name: multi_language/hi
additional_train_files: hi/train_hi.json
additional_dev_files: hi/dev_hi.json
additional_train_dev_files_sample_size: 0.1
additional_train_dev_files_use_stratified_sampling: true
test_file: hi/test_hi.json

defaults:
  - crosslang_en
